# Generated by Django 5.2.13 on 2026-05-09 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0010_alter_game_game_mode'),
        ('players', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='联赛系列名称')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='league_covers/', verbose_name='封面图')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_league_series', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'db_table': 'league_series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_number', models.PositiveIntegerField(verbose_name='届号/期号')),
                ('name', models.CharField(max_length=150, verbose_name='赛季名称')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='league_covers/', verbose_name='封面图')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述(Markdown+Base64图片)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='预计开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='预计结束时间')),
                ('status', models.CharField(choices=[('registration', '报名中'), ('ongoing', '进行中'), ('finished', '已结束')], default='registration', max_length=20, verbose_name='状态')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前期')),
                ('allow_online', models.BooleanField(default=True, verbose_name='允许线上对局')),
                ('allow_offline', models.BooleanField(default=True, verbose_name='允许线下录入')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_league_seasons', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagues.leagueseries', verbose_name='联赛系列')),
            ],
            options={
                'db_table': 'league_seasons',
                'ordering': ['-season_number'],
                'unique_together': {('series', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='LeagueStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='阶段名称')),
                ('stage_type', models.CharField(choices=[('swiss', '积分赛'), ('elimination_1', '淘汰赛第一阶段'), ('elimination_2', '淘汰赛第二阶段'), ('elimination_3', '淘汰赛第三阶段'), ('revival', '复活赛'), ('semifinal', '半决赛'), ('final', '决赛')], max_length=30, verbose_name='阶段类型')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('ongoing', '进行中'), ('finished', '已结束')], default='pending', max_length=20, verbose_name='阶段状态')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('games_per_player', models.PositiveIntegerField(default=8, verbose_name='每人半庄数')),
                ('uma_1st', models.FloatField(default=20, verbose_name='一位马点')),
                ('uma_2nd', models.FloatField(default=10, verbose_name='二位马点')),
                ('uma_3rd', models.FloatField(default=-10, verbose_name='三位马点')),
                ('uma_4th', models.FloatField(default=-20, verbose_name='四位马点')),
                ('base_score', models.FloatField(default=25000, verbose_name='基础分(返点)')),
                ('allow_companion', models.BooleanField(default=False, verbose_name='允许陪打')),
                ('allow_free_table', models.BooleanField(default=True, verbose_name='允许自由约桌')),
                ('record_ranking', models.BooleanField(default=False, verbose_name='记录段位分')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('promotion_rules', models.JSONField(blank=True, default=dict, verbose_name='晋级规则配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='leagues.leagueseason', verbose_name='赛季')),
            ],
            options={
                'db_table': 'league_stages',
                'ordering': ['order'],
                'unique_together': {('season', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LeagueMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_label', models.CharField(blank=True, default='', max_length=50, verbose_name='对局标签')),
                ('round_index', models.PositiveIntegerField(default=0, verbose_name='半决赛轮次/批次')),
                ('table_index', models.PositiveIntegerField(default=0, verbose_name='桌号')),
                ('scheduled_players', models.JSONField(blank=True, default=list, verbose_name='预设选手ID列表')),
                ('companion_players', models.JSONField(blank=True, default=list, verbose_name='陪打选手ID列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_match', to='games.game', verbose_name='关联对局')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.leaguestage', verbose_name='阶段')),
            ],
            options={
                'db_table': 'league_matches',
                'ordering': ['round_index', 'table_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueSeasonPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seed_label', models.CharField(blank=True, default='', max_length=10, verbose_name='种子签号(半决赛 A~H)')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_season_entries', to='players.player', verbose_name='雀士')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_players', to='leagues.leagueseason', verbose_name='赛季')),
            ],
            options={
                'db_table': 'league_season_players',
                'unique_together': {('season', 'player')},
            },
        ),
        migrations.CreateModel(
            name='LeagueStagePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_type', models.CharField(choices=[('winners', '胜者组'), ('losers', '败者组'), ('none', '无分组')], default='none', max_length=20, verbose_name='分组')),
                ('is_eliminated', models.BooleanField(default=False, verbose_name='是否淘汰')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='是否晋级')),
                ('games_played', models.PositiveIntegerField(default=0, verbose_name='已打半庄数')),
                ('total_pt', models.FloatField(default=0, verbose_name='累计PT')),
                ('rank_in_stage', models.PositiveIntegerField(default=0, verbose_name='当前排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_stage_entries', to='players.player', verbose_name='雀士')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_players', to='leagues.leaguestage', verbose_name='阶段')),
            ],
            options={
                'db_table': 'league_stage_players',
                'ordering': ['-total_pt'],
                'unique_together': {('stage', 'player')},
            },
        ),
    ]
