# Generated by Django 5.2.13 on 2026-04-23 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='等级名称')),
                ('level_order', models.IntegerField(unique=True, verbose_name='等级顺序')),
                ('initial_score', models.FloatField(default=0, verbose_name='初始分')),
                ('promotion_score', models.FloatField(default=0, verbose_name='升级所需pt')),
                ('dajiang_score', models.FloatField(default=10, verbose_name='打点分')),
                ('fourth_penalty', models.FloatField(default=0, verbose_name='第四额外扣点')),
                ('is_protected', models.BooleanField(default=False, verbose_name='是否保护段(不掉段)')),
                ('bg_color', models.CharField(default='#8e8e8e', max_length=20, verbose_name='背景颜色')),
                ('bg_gradient', models.CharField(blank=True, default='', max_length=100, verbose_name='渐变色')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='段位描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'rank_tiers',
                'ordering': ['level_order'],
            },
        ),
        migrations.CreateModel(
            name='UmaConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='场次名称')),
                ('player_count', models.SmallIntegerField(default=4, verbose_name='人数(3三麻/4四麻)')),
                ('game_mode', models.CharField(default='half_match', max_length=20, verbose_name='对局模式')),
                ('uma_1st', models.FloatField(default=30, verbose_name='一位马点')),
                ('uma_2nd', models.FloatField(default=10, verbose_name='二位马点')),
                ('uma_3rd', models.FloatField(default=-10, verbose_name='三位马点')),
                ('uma_4th', models.FloatField(default=-30, verbose_name='四位马点')),
                ('base_score', models.FloatField(default=250, verbose_name='基础分(返点)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'uma_configs',
                'ordering': ['player_count', 'game_mode'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRankingScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0, verbose_name='当前排位分')),
                ('game_count', models.IntegerField(default=0, verbose_name='对局数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_scores', to='players.player', verbose_name='雀士')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_scores', to='ranking.ranktier', verbose_name='当前段位')),
            ],
            options={
                'db_table': 'player_ranking_scores',
                'unique_together': {('player',)},
            },
        ),
    ]
