# Generated by Django 5.2.13 on 2026-04-23 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_room_room_type_session_time'),
        ('players', '0002_initial'),
        ('ranking', '0002_default_tiers_and_uma'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRankingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(verbose_name='顺位')),
                ('delta', models.FloatField(verbose_name='排位分变化')),
                ('old_tier_name', models.CharField(max_length=50, verbose_name='旧段位')),
                ('new_tier_name', models.CharField(max_length=50, verbose_name='新段位')),
                ('old_score', models.FloatField(verbose_name='旧排位分')),
                ('new_score', models.FloatField(verbose_name='新排位分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_results', to='games.game', verbose_name='对局')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_ranking_results', to='players.player', verbose_name='雀士')),
            ],
            options={
                'db_table': 'game_ranking_results',
                'unique_together': {('game', 'player')},
            },
        ),
    ]
