# Generated by Django 6.0.4 on 2026-04-20 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('offline', '线下对局'), ('online', '线上对局')], default='offline', max_length=20, verbose_name='对局类型')),
                ('game_mode', models.CharField(choices=[('east_wind', '东风局'), ('half_match', '半庄'), ('south_wind', '南风局')], default='east_wind', max_length=20, verbose_name='对局模式')),
                ('start_time', models.DateTimeField(verbose_name='对局时间')),
                ('source_url', models.URLField(blank=True, default='', verbose_name='牌谱链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.SmallIntegerField(verbose_name='座位号')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
                ('is_dealer_start', models.BooleanField(default=False, verbose_name='是否东起')),
            ],
            options={
                'db_table': 'game_players',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='房间名称')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='地点/雀庄')),
                ('status', models.CharField(choices=[('open', '进行中'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'db_table': 'room_players',
            },
        ),
    ]
