# Generated by Django 6.0.4 on 2026-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('east_wind', '东风'), ('half_match', '半庄')], default='east_wind', max_length=20, verbose_name='对局模式'),
        ),
    ]
