# Generated by Django 6.0.4 on 2026-04-20 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_game_mode'),
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('east_wind', '东风'), ('half_match', '半庄'), ('south_wind', '南风')], default='east_wind', max_length=20, verbose_name='对局模式'),
        ),
        migrations.CreateModel(
            name='HandRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('yakuman', '役满'), ('yakuman_confirmed', '役满确定'), ('yakuman_chance', '役满机会')], max_length=30, verbose_name='类型')),
                ('yakuman_name', models.CharField(max_length=100, verbose_name='役种名')),
                ('hand_tiles', models.JSONField(blank=True, default=list, verbose_name='手牌')),
                ('melds', models.JSONField(blank=True, default=list, verbose_name='吃碰杠牌')),
                ('winning_tile', models.CharField(blank=True, default='', max_length=10, verbose_name='胡牌张')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_records', to='games.game', verbose_name='对局')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_records', to='players.player', verbose_name='雀士')),
            ],
            options={
                'db_table': 'hand_records',
                'ordering': ['created_at'],
            },
        ),
    ]
