# Generated by Django 6.0.4 on 2026-04-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_game_mode_handrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.SmallIntegerField(choices=[(3, '三麻'), (4, '四麻')], default=4, verbose_name='人数(3三麻/4四麻)'),
        ),
    ]
