# Generated by Django 6.0.4 on 2026-04-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_add_player_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='handrecord',
            name='yakuman_name',
        ),
        migrations.AddField(
            model_name='handrecord',
            name='win_type',
            field=models.CharField(choices=[('tsumo', '自摸'), ('ron', '荣胡')], default='tsumo', max_length=10, verbose_name='胡牌方式'),
        ),
        migrations.AddField(
            model_name='handrecord',
            name='yakuman_names',
            field=models.JSONField(default=list, verbose_name='役种列表'),
        ),
    ]
