# Generated by Django 5.2.13 on 2026-04-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_add_win_type_and_yakuman_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='paipu_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='雀魂牌谱详细数据'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('east_wind', '东风'), ('half_match', '半庄')], default='east_wind', max_length=20, verbose_name='对局模式'),
        ),
    ]
