# Generated by Django 5.2.13 on 2026-05-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_add_game_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('east_wind', '东风'), ('half_match', '半庄')], default='half_match', max_length=20, verbose_name='对局模式'),
        ),
    ]
